project:
  type: website

website:
  title: "AB Paxtor Garcia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/paxabacus
      - icon: linkedin
        href: https://www.linkedin.com/in/ab-paxtor-garcia/
    
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



